import localFont from "next/font/local";
import "./globals.css";
import { AudioProvider } from "./context/AudioContext";
import { I18nProvider } from "./context/I18nContext";
import { ConfigProvider } from "./context/ConfigContext";
import Header from "./components/Header";
import BackgroundColorManager from "./components/BackgroundColorManager";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Let that sink in",
  description: "Generated by Jericho",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 生成favicon */}
      <link rel="icon" href="/favicon.ico" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider>
          <I18nProvider>
            <AudioProvider>
              <BackgroundColorManager />
              <Header />
              <main>{children}</main>
            </AudioProvider>
          </I18nProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
